// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace EFTest
{
    // Championships
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Championship
    {
        public int ChampionshipId { get; set; } // ChampionshipID (Primary key)
        public string Name { get; set; } // Name
        public string Prize { get; set; } // Prize

        // Reverse navigation
        public virtual ICollection<Event> Events { get; set; } // Events.FK__Events__Champion__34C8D9D1
        public virtual ICollection<Score> Scores { get; set; } // Scores.FK__Scores__Champion__398D8EEE
        
        public Championship()
        {
            Events = new List<Event>();
            Scores = new List<Score>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
