// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace EFTest
{
    // Manches
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Manch
    {
        public int MancheId { get; set; } // MancheID (Primary key)
        public string Name { get; set; } // Name
        public string Description { get; set; } // Description
        public int PlayerId { get; set; } // PlayerID
        public int RoundId { get; set; } // RoundID
        public int RunId { get; set; } // RunID
        public int TournamentId { get; set; } // TournamentID

        // Reverse navigation
        public virtual ICollection<Manch> Manches { get; set; } // Manches.FK__Manches__Tournam__3D5E1FD2

        // Foreign keys
        public virtual Manch Manch_TournamentId { get; set; } // FK__Manches__Tournam__3D5E1FD2
        public virtual Player Player { get; set; } // FK__Manches__PlayerI__3A81B327
        public virtual Round Round { get; set; } // FK__Manches__RoundID__3B75D760
        public virtual Run Run { get; set; } // FK__Manches__RunID__3C69FB99
        
        public Manch()
        {
            Manches = new List<Manch>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
