// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace EFTest
{
    // Teams
    public partial class TeamConfiguration : EntityTypeConfiguration<Team>
    {
        public TeamConfiguration()
            : this("dbo")
        {
        }
 
        public TeamConfiguration(string schema)
        {
            ToTable(schema + ".Teams");
            HasKey(x => x.TeamId);

            Property(x => x.TeamId).HasColumnName("TeamID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName("Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(10);
            Property(x => x.Place).HasColumnName("Place").IsRequired().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.MembershipNumber).HasColumnName("MembershipNumber").IsRequired().HasColumnType("int");
            Property(x => x.Delivery).HasColumnName("Delivery").IsRequired().HasColumnType("nvarchar").HasMaxLength(20);
            Property(x => x.President).HasColumnName("President").IsRequired().HasColumnType("nvarchar").HasMaxLength(20);
            Property(x => x.Address).HasColumnName("Address").IsRequired().HasColumnType("nvarchar").HasMaxLength(40);
            Property(x => x.License).HasColumnName("License").IsRequired().HasColumnType("nvarchar").HasMaxLength(40);
            Property(x => x.Logo).HasColumnName("Logo").IsRequired().HasColumnType("image").HasMaxLength(2147483647);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
