// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace EFTest
{
    // Timings
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Timing
    {
        public int TimingId { get; set; } // TimingID (Primary key)
        public DateTime Time { get; set; } // Time
        public int RunId { get; set; } // RunID

        // Reverse navigation
        public virtual ICollection<TimingType> TimingTypes { get; set; } // TimingTypes.FK__TimingTyp__Timin__36B12243

        // Foreign keys
        public virtual Run Run { get; set; } // FK__Timings__RunID__35BCFE0A
        
        public Timing()
        {
            TimingTypes = new List<TimingType>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
