// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace EFTest
{
    // TimingTypes
    public partial class TimingTypeConfiguration : EntityTypeConfiguration<TimingType>
    {
        public TimingTypeConfiguration()
            : this("dbo")
        {
        }
 
        public TimingTypeConfiguration(string schema)
        {
            ToTable(schema + ".TimingTypes");
            HasKey(x => x.TimingTypeId);

            Property(x => x.TimingTypeId).HasColumnName("TimingTypeID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.Type).HasColumnName("Type").IsRequired().HasColumnType("int");
            Property(x => x.TimingId).HasColumnName("TimingID").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Timing).WithMany(b => b.TimingTypes).HasForeignKey(c => c.TimingId); // FK__TimingTyp__Timin__36B12243
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
